---
name: SonarQube Analysis
on:
  push:
    branches:
      - main
jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \
          -Dsonar.projectKey=java \
          -Dsonar.projectName='java' \
          -Dsonar.host.url=http://13.126.119.218:9000 \
          -Dsonar.token=sqp_bedd7486965789b78fb2e313566d516c3f26eebe
